### ISSUE TITLE
GDAL Error for Windows

### ISSUE THREAD

**Issue by Sailor596** [ec-jrc/lisflood-code#108] opened 2022-08-14 16:30 UTC
I have tried for installing LISFLOOD, but I failed. I always encounter the "gdal" error. There have been users who encountered and solved the same error before. Could you please help?

I am doing this in Windows10 and python 3.8 environment. I have even installed GDAL from https://sandbox.idre.ucla.edu/sandbox/tutorials/installing-gdal-for-windows.

![Error](https://user-images.githubusercontent.com/111195948/184545941-77c47376-01cc-42de-80b9-970b4736a01b.jpg)

**Comment by valeriolorini** [comment] 2022-08-15 09:44
Dear Sailor596, thanks for reaching out. As written in an important  note in the read.me page of Lisflood code, the installation of Lisflood in a virtual env like conda in windows OS is difficult because of libraries availability  but also because you might want to leverage compilation for the routing parallel component. The note is here  https://github.com/ec-jrc/lisflood-code#important-note . To test the model you could use docker option described in the readme file. Alternatively, Win10 offers also the possibility to run a Linux box . If you achieve that you can successfully install conda and gdal without conflicts  as you were doing. I hope this helps.
Thanks, Valerio

**Comment by dudu2112** [comment] 2023-01-13 10:47
@Sailor596 Have you fixed your problem? I'm getting the same issue.

**Comment by diksha922** [comment] 2023-02-25 17:33
Hello team.

I am trying to install LISFLOOD using "Pypi packaged LISFLOOD and conda env" but facing issue with the installation.

It is showing "GDAL-error" **(Screenshot is attached for reference)**.

![Error1](https://user-images.githubusercontent.com/47293688/221371149-3f926ff6-51e1-4b0f-b9cd-ab7e53fe4cb2.PNG)

It is requested to kindly help me to install LISFLOOD in Windows 10. 

Quick response is highly appreciated.

**Comment by doc78** [comment] 2023-12-19 14:21
Duplicate of #122

**Closed by doc78** 2023-12-19 14:21 UTC
