### ISSUE TITLE
Problem with the initial tests on my Jupiter-noteBook

### ISSUE THREAD

**Issue by markdurel** [ec-jrc/lisflood-code#90] opened 2021-12-20 17:25 UTC
Hello community! I am having a problem with the pre-tests. I cloned the repository. Using the Binder launcher, I copied the code in order to work on my Jupiter-noteBook. Here is what I encounter. @StefaniaGrimaldi @domeniconappo 
I actually download Anaconda and am working with Jupiter-Notebook. Here is the link of the screenshot :  https://twitter.com/mak_durel/status/1472694708681981954/photo/1

**Comment by StefaniaGrimaldi** [comment] 2021-12-21 08:40
Hi @markdurel, we are pleased to know that you are working with LISFLOOD-OS! 

Thanks for sharing the screenshot: if my understanding is correct, you would like to run a test case using the Jupiter-notebook. In order to achieve this aim, you need a complete set-up with adequate settings.xml, forcings, and static maps. You can find a complete set-up for two different catchments in the repository https://github.com/ec-jrc/lisflood-usecases. You might also be interested in the branch https://github.com/ec-jrc/lisflood-usecases/tree/jupyter_notebook.

The path in your screenshot leads to the test folder inside the lisflood-code repository. That test folder contains the settings and the data that are required to complete the unit tests (by using "pytest"). The settings have options that are modified by the scripts of the unit tests (e.g. https://github.com/ec-jrc/lisflood-code/blob/master/tests/test_results.py), this means that everything works fine for the purpose of the unit tests when you run the command "pytest". However you can face problems if you try to use those settings individually. In the specific case of the screenshot, the run_lat_lon.xml is missing the line 
<setoption choice="1" name="repDischargeTs" /> : you can add it in line 76 of run_lat_lon.xml , however, it is likely that some other issue will come up. You can find a detailed description of the unit tests with "pytest" here: https://ec-jrc.github.io/lisflood-code/4_annex_tests/

I was wondering whether you have already tried to run LISFLOOD-OS using options B or C explained here https://ec-jrc.github.io/lisflood-code/3_step2_installation/ and if you had any problems with that.

Please let us know how you go, we will do our best to help.

**Comment by StefaniaGrimaldi** [comment] 2022-02-02 17:11
Hi @markdurel,

I will close this issue because you confirmed via e-mail that you correctly installed LISFLOOD-OS on your pc.

Please do not hesitate to let us know whether you have further questions.

Kind regards,
Stefania

**Closed by StefaniaGrimaldi** 2022-02-02 17:11 UTC

**Comment by markdurel** [comment] 2022-02-02 17:34
Hello! I was very happy to have found satisfaction. For the rest I will contact you. Good health to you!
